"""Add charging table

Revision ID: 12675ba27402
Revises: d224b05aa07b
Create Date: 2022-02-14 14:46:42.836895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12675ba27402'
down_revision = 'd224b05aa07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('kw_list', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('ampere_list', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('volt_list', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('socket_type_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('dc_support', sa.Boolean(), nullable=True),
    sa.Column('total_kw', sa.Float(), nullable=True),
    sa.Column('max_kw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charging')
    # ### end Alembic commands ###
