"""Adding new colums to adress table

Revision ID: d224b05aa07b
Revises: 39e4c6a79e2f
Create Date: 2022-02-14 14:35:55.535510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d224b05aa07b"
down_revision = "39e4c6a79e2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("address", sa.Column("street", sa.String(), nullable=True))
    op.add_column("address", sa.Column("town", sa.String(), nullable=True))
    op.add_column("address", sa.Column("district_old", sa.String(), nullable=True))
    op.add_column("address", sa.Column("district", sa.String(), nullable=True))
    op.add_column("address", sa.Column("state", sa.String(), nullable=True))
    op.add_column("address", sa.Column("country", sa.String(), nullable=True))
    op.add_column(
        "address", sa.Column("gmaps_latitude", sa.Float(precision=32), nullable=True)
    )
    op.add_column(
        "address", sa.Column("gmaps_longitude", sa.Float(precision=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("address", "gmaps_longitude")
    op.drop_column("address", "gmaps_latitude")
    op.drop_column("address", "country")
    op.drop_column("address", "state")
    op.drop_column("address", "district")
    op.drop_column("address", "district_old")
    op.drop_column("address", "town")
    op.drop_column("address", "street")
    # ### end Alembic commands ###
