"""some message

Revision ID: 42e102fa9c36
Revises: 
Create Date: 2021-12-14 15:08:59.742401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42e102fa9c36"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("house_number", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stations")
    # ### end Alembic commands ###
