"""city columns

Revision ID: 9a298d5411a0
Revises: 42e102fa9c36
Create Date: 2021-12-15 08:39:58.848107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a298d5411a0'
down_revision = '42e102fa9c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'city')
    # ### end Alembic commands ###
