"""add country code to stations table

Revision ID: 429ea1f92d8b
Revises: b7c9beaa5f8c
Create Date: 2023-01-10 12:53:46.141026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429ea1f92d8b'
down_revision = 'b7c9beaa5f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('country_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'country_code')
    # ### end Alembic commands ###
