"""adding point column with geography type and srid 4326 to stations table

Revision ID: 5b976b2d97af
Revises: d20d9aba14e7
Create Date: 2023-01-30 10:18:18.013353

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry, Geography


# revision identifiers, used by Alembic.
revision = '5b976b2d97af'
down_revision = 'd20d9aba14e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('point', Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'point')
    # ### end Alembic commands ###
