"""add is_merged as indicator if station is result of merge

Revision ID: d20d9aba14e7
Revises: 429ea1f92d8b
Create Date: 2023-01-20 10:47:01.750660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'd20d9aba14e7'
down_revision = '429ea1f92d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('is_merged', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    conn.execute(text("UPDATE stations SET is_merged = false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'is_merged')
    # ### end Alembic commands ###
