"""add merge status to stations table

Revision ID: d8b594a458e4
Revises: a82f42675356
Create Date: 2023-01-30 23:21:04.181725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b594a458e4'
down_revision = 'a82f42675356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('merge_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'merge_status')
    # ### end Alembic commands ###
