"""create separate table for source id of merged station

Revision ID: f3cec738ecd8
Revises: d8b594a458e4
Create Date: 2023-04-28 21:57:36.583128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'f3cec738ecd8'
down_revision = 'd8b594a458e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merged_station_source',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('merged_station_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('duplicate_source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["merged_station_id"], ["stations.id"],),
        sa.ForeignKeyConstraint(["duplicate_source_id"], ["stations.source_id"],),
        sa.PrimaryKeyConstraint("id")
    )
    conn = op.get_bind()
    conn.execute(text("""
    ALTER TABLE stations ALTER COLUMN source_id DROP NOT NULL;
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merged_station_source')
    conn = op.get_bind()
    conn.execute("""
    ALTER TABLE stations ALTER COLUMN source_id SET NOT NULL;
    """)
    # ### end Alembic commands ###
